export default {
  p1: 'The development coaches are part of the International Recruitment Team offering support to the trusts network for internationally educated nurses who are transitioning to working with Hertfordshire and West Essex.',
  p2: 'Their aim is to work with individual International Recruits to support ongoing career development and wellbeing. They can provide a blend of signposting, coaching, and pastoral support with career development skills and competence as you adapt to life in the UK and work in the NHS. They can assist with development opportuinities for rotation to other areas of nursing, if required.',
  p3: 'There are two development coaches who are aligned to the main acute trusts across Hertfordshire and West Essex',
  priscillahP1: 'Professionally l have worked in the NHS since l was 18 years old.  After training dually, l worked as a midwife, community outreach for vulnerble young adults (not called that anymore!), perinatal meantal health, safeguarding and as a team lead for that team and then training as a SCPHN (HV), worked in Learning disability, practice education.',
  priscillahP2: 'I used to be a union rep for ineqalities and am very passionate about our role professionally in relation to reducing ineqalities in heathcare.  Most of my roles have been around this.  I am also an advocate for mental health well being among health professionals and the wider community.  My MSc in health promotion and public health focused on mental health among a marginalised population and really empowered my practice. Having travelled and lived in a few countries, l consider the UK my home however l empathise with anyone who has left their home.',
  priscillahP3: 'Hobbies:  Reading, trekking, kayaking, country walks, travelling and a new found love for kundalini yoga.',
  lindaP1: 'I have 38 years of experience in the NHS as a nurse, midwife, and specialist practitioner – school nursing.  My journey has taken me through a range of roles working in hospitals to community-based school nursing, public health, child, and adolescent mental health.  My most recent role has been in nursing informatics and how technology can enhance the delivery of safer patient care.  Following early retirement in 2020, I returned to join the mass vaccination programme for covid 19, where I worked with many amazing people, nurses, administrators, and volunteers all working together and dedicated to reach one goal.',
  lindaP2: 'I am passionate about sharing my knowledge and supporting colleagues to develop to be the nurse they want to be and am excited to be working with international nursing recruits.',
  lindaP3: 'Hobbies: gardening, walking & spending time with family',
  lindaP4: '',
}