export default {
  p1: 'Each acute trust has an International Nurse Ambassador. They work within the hospital and are available for information and support on a day-to-day basis.',
  p2: 'Select your hospital trust for more information about your Nursing Ambassador.', 
  p3: '',
  pah1: 'I relocated to the UK since April 2019. I currently work as a discharge support nurse at a band 6. I have over 5 years experience in total as a registered nurse and midwife. I come from the East of Nigeria, and I practiced nursing for a few years back home.',
  pah2: 'My dream has always been to practice abroad. So, I started making enquires on how to go about it and so far since my relocation, I feel fulfilled that I had made the best choice and my interest is to advocate for the expansion of international recruitment for nurses globally.',
  pah3: 'I look forward to joining the team and contributing towards workforce recruitment and development in a positive way.',
  pah4: 'Hobbies:  Going on holidays',
  enh1: 'I am a registered nurse, trained in India, worked in 2 other countries, and arrived in UK in 2001, a time when the overseas nurse`s recruitment actively started in the NHS. I am experienced in various clinical specialities, completed mentorship training in University of Hertfordshire and attended leadership courses with various establishments in the UK.',
  enh2: 'I faced some challenges during the first year of transition, but my qualities of being easily adaptable and fast learning nature, I was able to handle them well and did not have any lasting impact on my career or life.',
  enh3: 'Currently, I am working as a clinical practice nurse in the acute service team, while supporting the senior team with managerial tasks that I learned as I progressed. I am known to have excellent leadership qualities, approachable and someone who goes above and beyond to help others.',
  enh4: 'I am interested in supporting our international nurses with their transition process into the role and into the community, and I believe this would empower them as they progress in their career.',
  enh5: 'I live with my husband and two teenage sons. My hobbies are being outdoors and watching TV',
  wh1: 'Ann is a Clinical night matron and will be able to provide additional support to overseas nurses in your area.',
  wh2: 'Ann has been working in our trust for the last 3 years and 9 months in total in NHS. ',
  wh3: 'She joined the NHS as an overseas nurse and worked as a ward manager. She supported overseas nurses in settling into their new environments and in progressing in their career path. ',
}